version: '3'

services:

### Applications Code Container #############################

    # web:
    #   image: debian:jessie
    #   volumes:
    #     - ./www:/var/www

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php
      volumes:
        - ../www:/var/www/html
      expose:
        - "9000"
      depends_on:
        - mysql
        - redis
        - memcached
      links:
        - memcached
        - redis

### PHP-CLI Container #######################################

    php-cli:
      build:
        context: ./php-cli
      volumes:
        - ../www:/var/www/html
      tty: true
      depends_on:
        - mysql
        - redis

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:
          - ../www:/var/www/html
      ports:
          - "8000:80"
          - "443:443"
      depends_on:
          - php-fpm

### MySQL Container #########################################

    mysql:
      image: daocloud.io/library/mysql:5.7
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        
### redis Container #############################
    redis:
      image: daocloud.io/library/redis
      restart: always
      expose:
        - "6379"
      ports:
        - "6379:6379"
      volumes:
        - ./data/redis:/data
      command: redis-server --appendonly yes 
    
### memecached Container ##########
    memcached:
      image: memcached
      expose:
        - "11211"
    
### PHPMyAdmin Container #########################################

    phpmyadmin:
      image: daocloud.io/daocloud/phpmyadmin
      ports:
        - "8080:80"
      links:
          - mysql:db

### Volumes Setup ###########################################

volumes:
    mysql-data:
